#!/bin/bash

set -e

read -r MEM_INFO </proc/meminfo
if [[ "${MEM_INFO}" =~ ^MemTotal:\ *([0-9]+)\ kB$ ]]; then
    MEM_KB=${BASH_REMATCH[1]}
else
    echo "Failed to read memory size!" >&2
    exit 1
fi

SIZE_KB=$(( MEM_KB ))

# probe zram
modprobe zram

# format zram
DEVNO="0"
BLKDEV="/dev/zram${DEVNO}"

echo "${SIZE_KB}K" > "/sys/block/zram${DEVNO}/disksize"

mkfs.ext4 -L SYSROOT "${BLKDEV}"

